### ISSUE TITLE
Error group by variables in Vector instead Tuple?

### ISSUE THREAD

**Issue by andreasnoack** [JuliaComputing/JuliaDB.jl#100]
I accidentally used a `Vector` instead of `Tuple` when I had two group variables and got something
```julia
julia> t=table([1,1,1,2,2,2], [1,1,2,2,1,1], [1,2,3,4,5,6],
                      names=[:x,:y,:z]);

julia> groupreduce(+, t, [:x, :y], select=:z)
Table with 2 rows, 2 columns:
1   2
─────
:x  1
:y  2
```
I think requiring tuples is fine but would it be possible to provide a meaningful error message?

The docstring uses `Selection` for the argument type but doesn't explain it. (The examples are great though)

**Comment by shashi** [comment]
Good catch.

Selection always refers to the 2nd argument in `select`. I think I can create a `const Selection = Any` and document that... Just need to figure out the flow of docs with this in it.
