### ISSUE TITLE
Load API

### ISSUE THREAD

**Issue by MikeInnes** [JuliaComputing/JuliaDB.jl#102]
```julia
Main> loadtable("lang-detection/data.csv")
ERROR: ArgumentError: Specified path does not refer to an existing directory.
```

It took me a while to figure out the most important function in this package.

My suggestion is to have a single `load` or `read` function which does the right thing with whatever input (files, folders, caches, lists of these things etc – even URLs, ideally). It can fall back to more specific functions like `load_table`, which are available if users want more control.

**Comment by shashi** [comment]
Where did you see `load_table`? It's not around anymore...

**Comment by MikeInnes** [comment]
Cool, thanks.

Is there a reason to have both `load_table` and `load`? Especially because `load` comes up first in autocomplete, it seems like the natural first thing to try, but appears to have a different purpose.

**Comment by shashi** [comment]
Not really a good reason to have load be different...

**Comment by Mirage10** [comment]
load_table is in the 0.6 * present ...

               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.1 (2017-10-24 22:15 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-pc-linux-gnu

julia> using JuliaDB

julia> load
load         load_table    loadfiles     loadndsparse  loadtable
julia> load
load         load_table    loadfiles     loadndsparse  loadtable
julia>
