### ISSUE TITLE
Change default value for cache in loadtable

### ISSUE THREAD

**Issue by andreasnoack** [JuliaComputing/JuliaDB.jl#113]
In my experience, it is often necessary to adjust the arguments a couple of times before they are right for a new dataset. Hence, it can be confusing that changing the arguments have no effect unless `cache=false` is specified. I think it would make more sense to have `cache=false` as default.

**Comment by shashi** [comment]
I've removed the caching feature since this was not very useful. You can now use `output=dir` to write the loaded output to a directory.
