### ISSUE TITLE
ndsparse test error with Julia 0.6.0

### ISSUE THREAD

**Issue by einzigsue** [JuliaComputing/JuliaDB.jl#115]
After installed JuliaD.jl I tested JuliaDB but got following error returned.

My julia version info is pasted below.
%%%%%%%%%%%%%%%%%%%%%%%%%
Julia Version 0.6.0
Commit 903644385b (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)

and the ndsparse test error message read as following.
%%%%%%%%%%%%%%%%%%%%%%%%%
ndsparse: Error During Test
  Got an exception of type MethodError outside of a @test
  MethodError: no method matching ndsparse(::IndexedTables.Columns{Tuple{Int64,String},Tuple{Array{Int64,1},Array{String,1}}})
  Closest candidates are:
    ndsparse(::IndexedTables.Columns, ::AbstractArray{T,1} where T; kwargs...) at /Users/Sue/Documents/Julia/.local/v0.6/IndexedTables/src/ndsparse.jl:207
    ndsparse(::AbstractArray{T,1} where T, ::Any; kwargs...) at /Users/Sue/Documents/Julia/.local/v0.6/IndexedTables/src/ndsparse.jl:199
    ndsparse(::Union{NamedTuples.NamedTuple, Tuple}, ::IndexedTables.Columns; kwargs...) at /Users/Sue/Documents/Julia/.local/v0.6/IndexedTables/src/ndsparse.jl:203
    ...
  Stacktrace:
   [1] macro expansion at /Users/Sue/Documents/Julia/.local/v0.6/JuliaDB/test/test_readwrite.jl:23 [inlined]
   [2] macro expansion at ./test.jl:860 [inlined]
   [3] anonymous at ./<missing>:?
   [4] include_from_node1(::String) at ./loading.jl:569
   [5] include(::String) at ./sysimg.jl:14
   [6] include_from_node1(::String) at ./loading.jl:569
   [7] include(::String) at ./sysimg.jl:14
   [8] process_options(::Base.JLOptions) at ./client.jl:305
   [9] _start() at ./client.jl:371
Test Summary: | Error  Total
ndsparse      |     1      1
ERROR: LoadError: LoadError: Some tests did not pass: 0 passed, 0 failed, 1 errored, 0 broken.
while loading /Users/Sue/Documents/Julia/.local/v0.6/JuliaDB/test/test_readwrite.jl, in expression starting on line 22
while loading /Users/Sue/Documents/Julia/.local/v0.6/JuliaDB/test/runtests.jl, in expression starting on line 15
================[ ERROR: JuliaDB ]==================

failed process: Process(`/Applications/Julia-0.6.app/Contents/Resources/julia/bin/julia -Ccore2 -J/Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes /Users/Sue/Documents/Julia/.local/v0.6/JuliaDB/test/runtests.jl`, ProcessExited(1)) [1]

=========================================================================
ERROR: JuliaDB had test errors

**Comment by shashi** [comment]
fixed by new releases
