### ISSUE TITLE
loadtable without header

### ISSUE THREAD

**Issue by catethos** [JuliaComputing/JuliaDB.jl#124]
Regarding the documentation here: https://github.com/JuliaComputing/JuliaDB.jl/blob/master/src/io.jl#L53

> - `colnames::Vector{String}` -- specify column names for the files, use this with (`header_exists=true`, otherwise first row is discarded). By default column names are assumed to be present in the file.

Shouldn't we set `header_exists=false` to keep the first row?

**Comment by shashi** [comment]
The documentation for this was wrong... Thanks!
