### ISSUE TITLE
rechunk can fail with FileRefs

### ISSUE THREAD

**Issue by tanmaykm** [JuliaComputing/JuliaDB.jl#136]
`rechunk` can fail [here]( https://github.com/JuliaComputing/JuliaDB.jl/blob/153d1b288a35388d9bc0d1848eb00f1c8cd56489/src/join.jl#L27) if there are `FileRef`s instead of `DRef`s. Because `Dagger.affinity` can return an empty array in the current implementaion [here](https://github.com/JuliaParallel/Dagger.jl/blob/881109e279b66f31709ab29d85671b3590621663/src/chunks.jl#L76).

Could falling back to deciding affinity using host IP be a valid solution?
ref: https://github.com/JuliaComputing/MemPool.jl/pull/4

**Comment by tanmaykm** [comment]
On second thoughts, I am not sure if JuliaDB should need to bother about affinity of chunks (`rechunk` should not specify hard affinities).

I think it should be left to Dagger to allocate tasks based on affinitity and its scheduling rules.

**Comment by shashi** [comment]
Fixed in the latest JuliaDB release (empty affinities are OK), and the latest MemPool and Dagger releases (they now give all procs on the node as affinity)
