### ISSUE TITLE
Deallocate in-core, distributed table

### ISSUE THREAD

**Issue by MaximilianJHuber** [JuliaComputing/JuliaDB.jl#165]
I `loadtable` a distributed table `t` in 5 chunks and 4 workers, save it and call `@everywhere gc(); gc()`, memory allocated by the workers decreases.

Then I call `t=0;' and again the GC everywhere, but memory stays constant, as if the workers held on to the data.

Is there a way I can force the workers to let go of the data?

**Comment by shashi** [comment]
`free!(tbl)` is the explicit way to do it. `gc()` should also call this, but may require more memory pressure than you have.
