### ISSUE TITLE
Convert Array of Arrays to Table

### ISSUE THREAD

**Issue by cdeterman** [JuliaComputing/JuliaDB.jl#173]
Let's say I have a 3x3 Array

    myarray = [[1,2,3],[4,5,6],[7,8,9]]

How can I convert this to a 3x3 `table`?  I tried

    table(myarray)

but this results in just a 3x1 table where each row is an array instead of three columns

**Comment by joshday** [comment]
Here you can do `table(myarray...)`

**Comment by cdeterman** [comment]
@joshday thank you, that nearly gets what I was after.  Is there a way to have it added rowwise?  Where the output of the `table` would be

```
Table with 3 rows, 3 columns:
1  2  3
───────
1  2  3
4  5  6
7  8  9
```

**Comment by joshday** [comment]
Tables get constructed (and store values) with vectors as columns, so you'll need to reshape the data first.  There may be a simpler way but this works:

```julia
julia> m = [myarray[i][j] for i in 1:3, j in 1:3]
3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

julia> table(m[:,1], m[:,2], m[:,3])
Table with 3 rows, 3 columns:
1  2  3
───────
1  2  3
4  5  6
7  8  9
```
