### ISSUE TITLE
Dimensions of Table

### ISSUE THREAD

**Issue by cdeterman** [JuliaComputing/JuliaDB.jl#174]
This feels like an embarrassingly simple question but I can't find anything in the JuliaDB docs and I haven't been able to stumble on the function.  I want to simply get the dimensions of the `table`.

For example, the following table

```
t = table([1,2,3],[4,5,6])
```

How do I get the dimensions (3,2)?  There appears to be no `size` method and I can't find anything that shows how to pull it otherwise.

**Comment by andreasnoack** [comment]
`length(t)` gives you the number of rows in `t` and `length(columns(t))` gives you the number of columns. Maybe there is a better way to get the number of columns but please ask questions on discourse.julialang.org.

**Comment by shashi** [comment]
That's as good as any to get the number of columns. We do have an `ncols` function, but I'm not sure it's ready to be exported.
