### ISSUE TITLE
inplace Column Modification

### ISSUE THREAD

**Issue by cdeterman** [JuliaComputing/JuliaDB.jl#181]
There are several functions for column modification (e.g. `pushcol`, `popcol`) but it appears that there aren't 'inplace' versions of them.  For example:

```jl
popcol!(mytable, :x)
```
>ERROR: UndefVarError: popcol! not defined
Stacktrace:
 [1] eval(::Module, ::Any) at .\boot.jl:235
 [2] eval(::Any) at .\boot.jl:234
 [3] macro expansion at C:\Users\userid\\.julia\v0.6\Atom\src\repl.jl:118 [inlined]
 [4] anonymous at .\<missing>:?

Inplace versions of these would be convenient.  Perhaps more efficient (avoid copy) as well but I don't know the internals of JuliaDB well enough to know how this is handled.

**Comment by piever** [comment]
You can just do `mytable = popcol(mytable, :x)`. It should be efficient and there's no way to make it in-place as the type of `mytable` is changing. The only thing that could be optimized is `setcol` when the new values are of the same value of the old values, see for example `@byrow!` [here](https://piever.github.io/JuliaDBMeta.jl/latest/row_macros.html#JuliaDBMeta.@byrow!). We could maybe implement a `setcol!` but it feels a bit inconsistent to only have one with in place version.

**Comment by shashi** [comment]
I'll close this. Let's open a new issue if we need `setcol!`.
