### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by ifynwosu** [JuliaComputing/JuliaDB.jl#185]
I'm trying to initialize a grid in Julia but I get an out of memory error when I try to read from stdin(commented out line). If I assign the size manually, it runs fine.

I added the print statement at the bottom to be sure I'm reading in correctly and it gives me the right output. I've searched all over but cant seem to be able to find a solution.

This isnt the full program I intend to write, but I want to be certain that reading in and writing out work properly before I proceed further.

I've attached my code below. Can anyone help with this?

Thanks

`
function main()
    
    i::UInt32 = 0
    j::UInt32 = 0
    interval::UInt32 = 0
    gridDifference::Float32 = 0.0
    stableValue::Float32 = 0.0
    MIN_FIXED_TEMP::Float32 = 0.0
    counter::Int32 = read(STDIN, Int32)
    NUM_ROWS::Int32 = read(STDIN, Int32)
    NUM_COLUMNS::Int32 = read(STDIN, Int32)
    EPSILON_VALUE::Float32 = read(STDIN, Int32)

    #initialGrid::Array{Float32,2} = read(STDIN, Float32, NUM_ROWS, NUM_COLUMNS)
    initialGrid::Array{Float32,2} = read(STDIN, Float32, 1024,1024)

    write(STDOUT, counter)
    write(STDOUT, EPSILON_VALUE)
    write(STDOUT, NUM_ROWS)
    write(STDOUT, NUM_COLUMNS)
    write(STDOUT, newGrid)

    print(STDERR,NUM_COLUMNS)

end

main()`

**Comment by shashi** [comment]
This is not a JuliaDB issue, it's a Julia issue.

You will get an out of memory error if you allocate an array that is bigger than your available memory...

For example if you have 4GB of RAM you can allocate up to 4GB of data (given all of it is free). This means a Float32 array of about 10^9 elements (each number is 4 bytes).

**Comment by ifynwosu** [comment]
Ok, thanks.

**Comment by shashi** [comment]
Oh, which thread on stackoverflow. Just curious

**Comment by ifynwosu** [comment]
this thread

[https://stackoverflow.com/questions/49868567/outofmemoryerror-in-julia?noredirect=1#comment86759384_49868567](url)
