### ISSUE TITLE
StringArray dependency causing precompile failure

### ISSUE THREAD

**Issue by jagrafft** [JuliaComputing/JuliaDB.jl#208]
StringArray is provided by StringArrays.jl, which is not a registered package and not included as a dependency.

Running ` Pkg.clone("https://github.com/JuliaComputing/StringArrays.jl.git")` and adding `__precompile__()` to the top of src/StringArrays.jl fixes issue.

**Comment by jagrafft** [comment]
May also need to add `using StringArrays` to src/util.jl.

**Comment by shashi** [comment]
StringArray is from WeakRefStrings.
I can't reproduce this on the latest release. Please reopen if you continue to face the issue.
