### ISSUE TITLE
ERROR: BoundsError: attempt to access 0×16×2 Array{Int8,3} at index [1:0, 0:15, 1:2]

### ISSUE THREAD

**Issue by algrosso** [JuliaComputing/JuliaDB.jl#244]

**Comment by algrosso** [comment]
I try to hcat an OffsetArray with indexes (0:-1, 0:-1,0:1) and size=(0,0,2) with another OffsetArray with indexes (0:-1,0:15,0:1) and size(0,16,2) and I get the error ERROR: BoundsError: attempt to access 0×16×2 Array{Int8,3} at index [1:0, 0:15, 1:2]
julia> form=OffsetArray(reshape(zeros(Int8,0),0,0,2),0:-1,0:-1,0:1)
julia> exp=OffsetArray(reshape(zeros(Int8,0),0,16,2),0:-1,0:15,0:1)
julia> hcat(form,exp)  Error!!

However if I try with arrays with indexes begining in 1
julia> form=reshape(zeros(Int8,0),0,0,2)
julia> exp=reshape(zeros(Int8,0),0,16,2)
juilia> hcat(form,exp)  woks!!!

Thanks

**Comment by joshday** [comment]
I think you opened an issue in the wrong place and perhaps you meant https://github.com/JuliaArrays/OffsetArrays.jl
