### ISSUE TITLE
groupby keep key

### ISSUE THREAD

**Issue by yakir12** [JuliaComputing/JuliaDB.jl#278]
This has bothered me a fair amount: you `groupby` a table by a `key` and the value of the grouping key is not included in the result. I'm not sure, maybe this is standard DB behavior, but I often need to perform some action on a group and need to know what the common key of each of the group's members is. I might be alone on this one...

**Comment by piever** [comment]
It's already implemented but missing docs. You can do:
```julia
groupby(t, by; usekey = true) do key, dd
   # code using key as key (named tuple) and dd as data
end
```

But somehow this was never added to the docstring

**Comment by yakir12** [comment]
Hope that helps :)
