### ISSUE TITLE
Can't load csv file downloaded from Canadian Gov Web Site, but R can

### ISSUE THREAD

**Issue by tarjin** [JuliaComputing/JuliaDB.jl#283]
https://www150.statcan.gc.ca/n1/tbl/csv/35100178-eng.zip

Using JuliaDB there is an error and it won't load. But with R, using data.tables and fread there is no problem. 

Steps:
1. Download the csv file
2. try using loadtable with that csv file

Result:
lot's of errors that I don't have a screenshot for right now.

Expected:
Load it quickly as fread in R without errors, or just be able to load it all in under two minutes. 

Environment: The csv file is about 3.7 GB, just under 16 million rows and 16 columns. I am working with Julia 1.1.0 and 1.1.1.

p.s.: I will attach screenshots soon.

**Comment by tarjin** [comment]
Here is a screenshot of what I'm experiencing.

![Capture](https://user-images.githubusercontent.com/30064009/58296951-40694b00-7dac-11e9-913a-97e1672bdf6f.PNG)

**Comment by MaximilianJHuber** [comment]
```
loadtable("C:\\Users\\Max\\Desktop\\35100178.csv", type_detect_rows = 10000)
```

does the trick. Loading from an SSD takes 36 seconds (including some compile time). Checkout `?loadtable` for all options. The fact that `"` is the default `quotechar` may have something to do with this error.

**Comment by davidanthoff** [comment]
Ideally we would move this issue over to TextParse.jl. I initially thought the problem here is just that we incorrectly detect the type of the column, but I think there might be something else going on as well.

**Comment by tarjin** [comment]
Thank you!!! i will surely try this tomorrow. I appreciate the help, and the confidence knowing reading large CSV files can be done quickly in the Julia ecosystem. I'll post back after I try your solution.  Thanks for looking into it.

**Comment by tarjin** [comment]
![JuliaDB](https://user-images.githubusercontent.com/30064009/58364783-c3af9d00-7e8f-11e9-9490-d3d267a85e20.png)

This worked! Thanks so much. I still have to read and understand what "type_detect_rows = 10000"  did to fix this, but thank you. In coles notes, can you describe why that made this work? Much appreciated as I work a lot with Stats Canada csv files.

**Comment by tarjin** [comment]
Well, I think "type_detect_rows = 10000" is guesswork right now. It isn't reliable when I change that value lower, and if I change it higher the load time increases. So, in a way, it's not predictable what this value should be set to.  Maybe I'm wrong.  My alternative solution is to break up the big csv file into 16 smaller csv files of 1 million rows each. Then load and combine each one with CSV.jl.  This does work, and in a function it's about 100 seconds or thereabouts. Rust has a great command line tool called xsv that splits a big csv file really quickly into a collection of smaller files. Then CSV.jl can read each one with CSV.read(file) without any problem. Note, CSV.jl also can't read this larger CSV file. Truly frustrating.

**Comment by MaximilianJHuber** [comment]
The best thing would be to provide column types to `loadtable`. 
Maybe read up on JuliaDB's "Out-of-core processing" abilities.
I believe this is not the place to to discuss specific use cases, though. https://discourse.julialang.org/ and the JuliaDB channel on Slack is the place to ask those questions.
I suggest following @davidanthoff and opening an issue with TextParse.jl so that the `""` may not throw an error in the future and closing this issue.

**Comment by tarjin** [comment]
Thank you, very much appreciated.

**Comment by davidanthoff** [comment]
@joshday could you reopen this issue and move it over to TextParse? Thanks!
