### ISSUE TITLE
KeyError: key Dagger [d58978e5-989f-55fb-8d15-ea34adc7bf54] not found; when using function loadtable 

### ISSUE THREAD

**Issue by dingbo8128** [JuliaComputing/JuliaDB.jl#284]
julia --project=. -p 4

julia> using JuliaDB, DelimitedFiles
[ Info: Recompiling stale cache file /Users/bo/.julia/compiled/v1.1/JuliaDB/4FA8g.ji for JuliaDB [a93385a2-3734-596a-9a66-3cfbb77141e6]

julia> t = loadtable("/Users/bo/Data/keyword0112/data.csv")
ERROR: On worker 2:
KeyError: key Dagger [d58978e5-989f-55fb-8d15-ea34adc7bf54] not found
getindex at ./dict.jl:478 [inlined]
root_module at ./loading.jl:898 [inlined]
deserialize_module at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Serialization/src/Serialization.jl:890
handle_deserialize at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Serialization/src/Serialization.jl:795
deserialize at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Serialization/src/Serialization.jl:731
deserialize_datatype at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Serialization/src/Serialization.jl:1114
handle_deserialize at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Serialization/src/Serialization.jl:771
deserialize at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Serialization/src/Serialization.jl:731
handle_deserialize at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Serialization/src/Serialization.jl:778
deserialize_msg at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Serialization/src/Serialization.jl:731
#invokelatest#1 at ./essentials.jl:742 [inlined]
invokelatest at ./essentials.jl:741 [inlined]
message_handler_loop at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Distributed/src/process_messages.jl:160
process_tcp_streams at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Distributed/src/process_messages.jl:117
#105 at ./task.jl:259
#remotecall_fetch#149(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Function, ::Distributed.Worker, ::Dagger.Context, ::Vararg{Any,N} where N) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Distributed/src/remotecall.jl:379
remotecall_fetch(::Function, ::Distributed.Worker, ::Dagger.Context, ::Vararg{Any,N} where N) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Distributed/src/remotecall.jl:371
#remotecall_fetch#152(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Function, ::Int64, ::Dagger.Context, ::Vararg{Any,N} where N) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Distributed/src/remotecall.jl:406
remotecall_fetch at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Distributed/src/remotecall.jl:406 [inlined]
macro expansion at /Users/bo/.julia/packages/Dagger/sdZXi/src/scheduler.jl:272 [inlined]
(::getfield(Dagger.Sch, Symbol("##13#14")){Dagger.Context,Dagger.OSProc,Int64,getfield(JuliaDB, Symbol("##190#193")){Array{Any,1},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},UnionAll},Tuple{Array{String,1}},Channel{Any},Bool,Bool,Bool})() at ./task.jl:259
Stacktrace:
 [1] compute_dag(::Dagger.Context, ::Dagger.Thunk) at /Users/bo/.julia/packages/Dagger/sdZXi/src/scheduler.jl:62
 [2] compute(::Dagger.Context, ::Dagger.Thunk) at /Users/bo/.julia/packages/Dagger/sdZXi/src/compute.jl:25
 [3] #fromchunks#47(::Nothing, ::Int64, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Array{Dagger.Thunk,1}) at /Users/bo/.julia/packages/JuliaDB/jDAlJ/src/table.jl:148
 [4] (::getfield(JuliaDB, Symbol("#kw##fromchunks")))(::NamedTuple{(:output, :fnoffset),Tuple{Nothing,Int64}}, ::typeof(JuliaDB.fromchunks), ::Array{Dagger.Thunk,1}) at ./none:0
 [5] #_loadtable#188(::Nothing, ::Nothing, ::Bool, ::Array{Any,1}, ::Bool, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Type, ::String) at /Users/bo/.julia/packages/JuliaDB/jDAlJ/src/io.jl:140
 [6] _loadtable at /Users/bo/.julia/packages/JuliaDB/jDAlJ/src/io.jl:95 [inlined]
 [7] #loadtable#186 at /Users/bo/.julia/packages/JuliaDB/jDAlJ/src/io.jl:63 [inlined]
 [8] loadtable(::String) at /Users/bo/.julia/packages/JuliaDB/jDAlJ/src/io.jl:63
 [9] top-level scope at none:0

(AzmSel) pkg> status
    Status `~/Source/Julia/AzmSel/Project.toml`
  [a93c6f00] DataFrames v0.18.3
  [a93385a2] JuliaDB v0.12.0

**Comment by joshday** [comment]
Does `@everywhere using JuliaDB` solve the issue?

**Comment by dingbo8128** [comment]
does worker2 run in different path from current worker ?  
julia> @everywhere using JuliaDB, DelimitedFiles
ERROR: On worker 2:
ArgumentError: Package JuliaDB not found in current path:
- Run `import Pkg; Pkg.add("JuliaDB")` to install the JuliaDB package.

**Comment by jpsamaroo** [comment]
Your remote (or local) workers need to have JuliaDB in their main environment, I believe. I don't think workers load the same project as the master. This is a quirk (bug?) in how Julia's Distributed handles package loading on workers.

**Comment by jpsamaroo** [comment]
@joshday I think this issue should be closed. @dingbo8128 feel free to reply back here if you're still having issues (or post to https://discourse.julialang.org/ to get a wider audience).
