### ISSUE TITLE
Failed adding under Julia 1.2.0 rc1

### ISSUE THREAD

**Issue by ZHENGSY** [JuliaComputing/JuliaDB.jl#290]
Pls have a look.
--------------------------------
(v1.2) pkg> add JuliaDB
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package PooledArrays [2dfb63ee]:
 PooledArrays [2dfb63ee] log:
 ├─possible versions are: [0.0.1-0.0.2, 0.1.0-0.1.1, 0.2.0-0.2.2, 0.3.0, 0.4.0-0.4.1, 0.5.0-0.5.2] or uninstalled
 ├─restricted by compatibility requirements with DataFrames [a93c6f00] to versions: 0.5.0-0.5.2
 │ └─DataFrames [a93c6f00] log:
 │   ├─possible versions are: [0.1.0, 0.2.0-0.2.5, 0.3.0-0.3.16, 0.4.0-0.4.3, 0.5.0-0.5.12, 0.6.0-0.6.11, 0.7.0-0.7.8, 0.8.0-0.8.5, 0.9.0-0.9.1, 0.10.0-0.10.1, 0.11.0-0.11.7, 0.12.0, 0.13.0-0.13.1, 0.14.0-0.14.1, 0.15.0-0.15.2, 0.16.0, 0.17.0-0.17.1, 0.18.0-0.18.4] or uninstalled
 │   └─restricted to versions 0.18.4 by an explicit requirement, leaving only versions 0.18.4
 └─restricted by compatibility requirements with JuliaDB [a93385a2] to versions: [0.0.2, 0.1.0-0.1.1] — no versions left
   └─JuliaDB [a93385a2] log:
     ├─possible versions are: [0.1.0-0.1.5, 0.2.0-0.2.3, 0.3.0-0.3.7, 0.4.0-0.4.4, 0.5.0, 0.6.0, 0.7.0-0.7.2, 0.8.0-0.8.5, 0.9.0, 0.10.0, 0.11.0-0.11.2, 0.12.0] or uninstalled
     ├─restricted to versions * by an explicit requirement, leaving only versions [0.1.0-0.1.5, 0.2.0-0.2.3, 0.3.0-0.3.7, 0.4.0-0.4.4, 0.5.0, 0.6.0, 0.7.0-0.7.2, 0.8.0-0.8.5, 0.9.0, 0.10.0, 0.11.0-0.11.2, 0.12.0]
     └─restricted by compatibility requirements with OnlineStats [a15396b6] to versions: [0.1.0-0.1.5, 0.2.0-0.2.3, 0.3.0-0.3.6] or uninstalled, leaving only versions: [0.1.0-0.1.5, 0.2.0-0.2.3, 0.3.0-0.3.6]
       └─OnlineStats [a15396b6] log:
         ├─possible versions are: [0.1.0-0.1.3, 0.2.0, 0.3.0, 0.4.0, 0.5.0-0.5.4, 0.6.0, 0.7.0-0.7.1, 0.8.0, 0.9.0-0.9.1, 0.10.0-0.10.1, 0.11.0-0.11.1, 0.12.0-0.12.1, 0.13.0-0.13.2, 0.14.0-0.14.1, 0.15.0-0.15.4, 0.16.0, 0.17.0-0.17.5, 0.18.0, 0.19.0-0.19.2, 0.20.1-0.20.3, 0.21.0, 0.22.0, 0.23.0, 0.24.0, 0.25.0, 0.26.0-0.26.1] or uninstalled
         └─restricted to versions 0.26.1 by an explicit requirement, leaving only versions 0.26.1

**Comment by appleparan** [comment]
It's a simple issue because JuliaDB doesn't release new version since March.

`REQUIRE` restricts version of some dependencies. Using `REQUIRE` in 2019 is quite surprising thing, but I wait camly new version because `IndexedTables.jl` has started to use `Project.toml` in recent version. I expect authors will update this someday.

**Comment by ZHENGSY** [comment]
I worked this around by:

pkg1.3>remove PooledArrays
pkg1.3>add JuliaDB
pkg1.3>add PooledArrays

Done.

But like to see new release. :)

**Comment by appleparan** [comment]
My usual temporal workaround for similiar issue is 

```
(1.1) pkg ] add JuliaDB#master
```
