### ISSUE TITLE
JuliaDB.load FileIO.load conflicting

### ISSUE THREAD

**Issue by rapus95** [JuliaComputing/JuliaDB.jl#307]
How comes that nobody ran into this before?
```julia
julia> using FileIO, JuliaDB
julia> load
WARNING: both JuliaDB and FileIO export "load"; uses of it in module Main must be qualified
ERROR: UndefVarError: load not defined
```

Could this be resolved by redirecting through FileIO? As the function doesn't read files I guess no 🤔 Nevertheless would be cool if that would be resolved.

**Comment by joshday** [comment]
Given how many packages there are that can read CSVs, my first guess is that FileIO integration would be more trouble than it's worth.

JuliaDB can also read all of the CSVs in a directory, a use case I don't think can be directly handled with FileIO.

**Comment by xiaodaigh** [comment]
```
using FileIO:FileIO, JuliaDB
load
FileIO.load
```

**Comment by jpsamaroo** [comment]
I'm going to close this since I can't think of any reasonable solution that doesn't negatively impact one or both packages; feel free to re-open if anyone has a good solution!

**Comment by rapus95** [comment]
Well, If neither wants to consider going a few characters away from "load" then you are right, I guess.
Thus, the primary question is, whether it could be considered for JuliaDB to change the name to something similar meaningful but less colliding.
