### ISSUE TITLE
How to select a variable using its name (of type String)?

### ISSUE THREAD

**Issue by xinkai-zhou** [JuliaComputing/JuliaDB.jl#313]
Say I have the same table as in this example:
https://juliacomputing.github.io/JuliaDB.jl/latest/basics/#Selectors-1

`t = table(1:10, randn(10), rand(Bool, 10); names = [:x, :y, :z])`

To select the `x` column, the example code shows `select(t, :x)`. But how can I get it by using the character string `"x"`? `select(t, "x")` does not work. 

In R I can do t[, "x"] using base, or select_(t, "x") using the dplyr package. 

Thanks.

**Comment by joshday** [comment]
You can use a regex, like `select(t, r"x")`

**Comment by xinkai-zhou** [comment]
Thank you for the reply. I have two followup questions:

1. When I use ```select(t, :x)```, I get an array; but when I use ```select(t, r"x")```, I get an IndexTable. I can use ```select(select(t, r"x"), 1)``` to get the array, but I assume there are better ways to convert IndexTables to arrays? 

2. When the variables that I want to select is in a vector, say ```vars = ["x", "y"]```, how can I perform ```select```? I tried ```select(t, (r"x", r"y"))``` and here is the output 

```
Table with 10 rows, 2 columns:
1          2
───────────────────────────
(x = 1,)   (y = -0.431077,)
(x = 2,)   (y = 0.34282,)
(x = 3,)   (y = 0.94731,)
(x = 4,)   (y = -1.17977,)
(x = 5,)   (y = 0.622132,)
(x = 6,)   (y = -1.04549,)
(x = 7,)   (y = 0.0556006,)
(x = 8,)   (y = -0.101283,)
(x = 9,)   (y = -1.30898,)
(x = 10,)  (y = -1.36948,)
```

which is different from what I get using ```select(t, (:x, :y))```:

```
Table with 10 rows, 2 columns:
x   y
─────────────
1   -0.431077
2   0.34282
3   0.94731
4   -1.17977
5   0.622132
6   -1.04549
7   0.0556006
8   -0.101283
9   -1.30898
10  -1.36948
```

**Comment by piever** [comment]
The regex selects _all_ matching columns as a table. To get just one column by name, you need to use a `Symbol`. If you only have the name as `String`, you need to convert, i.e.
```julia
select(t, Symbol("x"))
```
or, for more than one,
```julia
select(t, map(Symbol, ("x", "y")))
```

**Comment by jpsamaroo** [comment]
@xinkai-zhou did the posted solutions work for you?

**Comment by xinkai-zhou** [comment]
@jpsamaroo Yes, I will close the issue now. Thanks everyone!
