### ISSUE TITLE
https://juliadb.org is down

### ISSUE THREAD

**Issue by alexander-matsievsky** [JuliaComputing/JuliaDB.jl#319]
Hi!

Right now https://juliadb.org seems to be down:

![image](https://user-images.githubusercontent.com/3784691/75149076-2fba7c80-5712-11ea-99a2-b62c0cfd8640.png)

Meanwhile https://downforeveryoneorjustme.com/juliadb.org reports the domain is up:

![image](https://user-images.githubusercontent.com/3784691/75149144-5973a380-5712-11ea-9a21-02cf28fe0dcd.png)

but links to insecure http://juliadb.org:

![image](https://user-images.githubusercontent.com/3784691/75149205-81fb9d80-5712-11ea-953f-0f5b0302c918.png)

**Is everything's fine or a domain takeover's going on?**

**Comment by alexander-matsievsky** [comment]
Seems like I overreacted and it's legit:

![image](https://user-images.githubusercontent.com/3784691/75150393-4dd5ac00-5715-11ea-9240-be70f2d4e70e.png)

But the site's down right now anyway. Feel free to close this issue if that's just a short maintenance matter.

**Comment by mkitti** [comment]
@Keno said it was being worked on: https://julialang.slack.com/archives/C67910KEH/p1582575723322900

**Comment by alexander-matsievsky** [comment]
@mkitti Great! Thank you, Mark!
