### ISSUE TITLE
ingest should be loadfiles + save

### ISSUE THREAD

**Issue by shashi** [JuliaComputing/JuliaDB.jl#36]
Right now we have 2 different implementations of this very similar functionality.

**Comment by diegozea** [comment]
Could it be a problem, in terms of RAM usage, with really huge CSV files?

**Comment by shashi** [comment]
Well, it's possible to read and save each chunk separately (or < N chunks at a time), so huge CSV files should be okay as long as a subset of them fit in memory.. Very close to implementing this...
