### ISSUE TITLE
Support for GZ file extension (custom file format)

### ISSUE THREAD

**Issue by hpoit** [JuliaComputing/JuliaDB.jl#46]
Hello! Would like to inform that as of tomorrow I'll be working on building a PR for this. Any preferred references are welcome. For the moment I'm studying Libz.jl.

**Comment by hpoit** [comment]
I am closing this issue as I understand types in the IO namespace will be used to interact with files (including compressed) and directories.

**Comment by JeffBezanson** [comment]
I'm not sure this should be tied to operating on generic I/O streams. The problem with an I/O stream is you don't know how to recreate it, while it's safe to assume you can re-read a file given a path. I think the most straightforward approach is to add support for custom file formats, and add .csv.gz by combining GZip.jl and the current csv reader.

**Comment by hpoit** [comment]
Use GZip.jl, not Libz.jl? By current csv reader I understand CSV.jl?

**Comment by hpoit** [comment]
Jeff, what do you think of these general instructions? 

Get Libz.jl and ZipFile.jl to comply with FileIO.jl API, so that `load("x.gz")` or `load("x.zip")` will use those packages to read those files respectively. If `load` returned an uncompressed I/O stream then we can just pass that to `TextParse.csvread` from JuliaDB.

The benefit of this approach is that JuliaDB depends only on FileIO.jl, which has no dependencies other than Compat, and is meant to support exactly this situation.

**Comment by andreasnoack** [comment]
Fixed by https://github.com/JuliaComputing/TextParse.jl/pull/44
