### ISSUE TITLE
Support for memory-mapped I/O

### ISSUE THREAD

**Issue by hpoit** [JuliaComputing/JuliaDB.jl#49]
References
https://msdn.microsoft.com/en-us/library/dd997372(v=vs.110).aspx
https://docs.julialang.org/en/stable/stdlib/io-network/#memory-mapped-i-o
[Passing the byte array representation of the mapped segment as source](https://github.com/JuliaLang/julia/blob/6e0a2f8c94f050faa4a4997757037a4f9754866d/base/datafmt.jl)

I will work on this after supporting I/O streams.

**Comment by JeffBezanson** [comment]
The format used by `ingest` already does this.
