### ISSUE TITLE
BoundsError: attempt to access 0-element Array{Any,1} at index [0]

### ISSUE THREAD

**Issue by svaksha** [JuliaComputing/JuliaDB.jl#58]
Another `Dagger.jl` related error.
```
julia> sampledata = loadfiles(path, indexcols=["date", "ticker"])
Metadata for 6 / 7 files can be loaded from cache.
Reading 1 csv files totalling 63 bytes...
ERROR: BoundsError: attempt to access 0-element Array{Any,1} at index [0]
#_csvread#28(::Char, ::Char, ::Array{Any,1}, ::Array{Any,1}, ::Bool, ::Int64, ::Bool, ::Array{String,1}, ::Array{Any,1}, ::Int64, ::TextParse.#_csvread, ::WeakRefString{UInt8}, ::Char) at /home/jn/.julia/v0.7/TextParse/src/csv.jl:104
#csvread#27(::Array{Any,1}, ::Function, ::IOStream, ::Char) at /home/jn/.julia/v0.7/TextParse/src/csv.jl:64
#25 at /home/jn/.julia/v0.7/TextParse/src/csv.jl:58 [inlined]
open(::TextParse.##25#26{Array{Any,1},Char}, ::String, ::String) at ./iostream.jl:152
#load_table#7(::Array{String,1}, ::Void, ::Void, ::Bool, ::Bool, ::TextParse.#csvread, ::Array{Any,1}, ::Function, ::String, ::Char) at /home/jn/.julia/v0.7/JuliaDB/src/util.jl:152
(::JuliaDB.#kw##load_table)(::Array{Any,1}, ::JuliaDB.#load_table, ::String, ::Char) at ./<missing>:0
_gather(::Dagger.Context, ::JuliaDB.CSVChunk) at /home/jn/.julia/v0.7/JuliaDB/src/loadfiles.jl:185
#makecsvchunk#112(::Bool, ::Array{Any,1}, ::Function, ::String, ::Char) at /home/jn/.julia/v0.7/JuliaDB/src/loadfiles.jl:210
(::JuliaDB.#kw##makecsvchunk)(::Array{Any,1}, ::JuliaDB.#makecsvchunk, ::String, ::Char) at ./<missing>:0
(::JuliaDB.#load_f#92{Array{Any,1},Char})(::String) at /home/jn/.julia/v0.7/JuliaDB/src/loadfiles.jl:107
do_task(::Dagger.Context, ::Dagger.OSProc, ::Int64, ::Function, ::Tuple{String}, ::Bool, ::Bool) at /home/jn/.julia/v0.7/Dagger/src/compute.jl:449
(::Base.Distributed.##135#136{Dagger.#do_task,Tuple{Dagger.Context,Dagger.OSProc,Int64,JuliaDB.#load_f#92{Array{Any,1},Char},Tuple{String},Bool,Bool},Array{Any,1}})() at ./distributed/remotecall.jl:314
run_work_thunk(::Base.Distributed.##135#136{Dagger.#do_task,Tuple{Dagger.Context,Dagger.OSProc,Int64,JuliaDB.#load_f#92{Array{Any,1},Char},Tuple{String},Bool,Bool},Array{Any,1}}, ::Bool) at ./distributed/process_messages.jl:56
#remotecall_fetch#140(::Array{Any,1}, ::Function, ::Function, ::Base.Distributed.LocalProcess, ::Dagger.Context, ::Vararg{Any,N} where N) at ./distributed/remotecall.jl:339
remotecall_fetch(::Function, ::Base.Distributed.LocalProcess, ::Dagger.Context, ::Vararg{Any,N} where N) at ./distributed/remotecall.jl:339
#remotecall_fetch#144(::Array{Any,1}, ::Function, ::Function, ::Int64, ::Dagger.Context, ::Vararg{Any,N} where N) at ./distributed/remotecall.jl:367
macro expansion at /home/jn/.julia/v0.7/Dagger/src/compute.jl:462 [inlined]
(::Dagger.##122#123{Dagger.Context,Dagger.OSProc,Int64,JuliaDB.#load_f#92{Array{Any,1},Char},Tuple{String},Channel{Any},Bool,Bool})() at ./event.jl:73
```

**Comment by shashi** [comment]
> `Dagger.jl` related error

It's not. Everything in JuliaDB executes through Dagger, that's why you can see it in the backtrace. The error is happening [here](https://github.com/JuliaComputing/TextParse.jl/blob/master/src/csv.jl#L104). It seems the extra file you're trying to load somehow has 0 columns. Can you send me / paste the file here?

**Comment by svaksha** [comment]
I was trying out the example in the docs: https://github.com/JuliaComputing/JuliaDB.jl/blob/master/docs/src/index.md#loading-csv-files

**Comment by shashi** [comment]
But there are only 6 files in that directory (`path`), it seems you put another file in there?

**Comment by shashi** [comment]
Okay hold on, I think I know what's happening.

**Comment by shashi** [comment]
Nope, I can't reproduce this. Which OS are you on?

**Comment by svaksha** [comment]
I didnt add any files. OS: Ubuntu 17.04 and julia version is : 
```
  | | |_| | | | (_| |  |  Version 0.7.0-DEV.94 (2017-05-11 04:21 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 4dbfe4b31d (21 days old master)
|__/                   |  x86_64-linux-gnu
```

**Comment by shashi** [comment]
Ohh 0.7.0-DEV I see. Can you try it on Julia 0.6-rc2?

**Comment by shashi** [comment]
The example won't work on 0.7 for other reasons anyway

**Comment by svaksha** [comment]
Do you have a branch[1] that works with *-DEV that I can clone? The rest of my code is on 0.7, so if this lib worked with distributed csv files it would be less painful to test and change code than test everything on 0.6-rc. 

[1] It would be nicer if the packages also followed the julia  (git master => tested on DEV versions) release cycle, than the current stable methodology. Multiple package styles are confusing. Just thinking out loud.

**Comment by shashi** [comment]
> Do you have a branch

No there's no version right now that works on 0.7, we need to fix some issues in NamedTuples to work on the 0.7.

**Comment by JeffBezanson** [comment]
It's not reasonable to expect master branches of julia and many packages to all be kept in sync. Yes it's nice if it can be done, but tagging released versions is the only real way to get things compatible.

**Comment by Andy-xu-007** [comment]
I have the same problem, it's so confused: the following code is only a fragment
`
println(typeof(page_store))  # Array{String,1}
println(length(page_store)) # 101
for ii = 1:length(page_store)
    println(ii)  # 0
    println(page_store[ii]) # ERROR: LoadError: BoundsError: attempt to access 101-element Array{String,1} at index [0]
`
Julia version is 1.0.2
Sorry, i have no way to solve this problem and i don't know what happen, why the parameter ii change to 0, so if you have solve this problem, please, tell me why,
thanks in advance

**Comment by joshday** [comment]
@Andy-xu-007 A couple things:

- It doesn't look like your problem is related to JuliaDB, so this is the wrong place to ask.  Try the Julia slack or discourse.
- When you post on slack or discourse, post an example that other people can reproduce.  It's much easier for people to offer help that way.
