### ISSUE TITLE
JuliaDB and NamedTuples out of sync: no create_tuple found

### ISSUE THREAD

**Issue by merl-dev** [JuliaComputing/JuliaDB.jl#59]
Just a heads up:  I noticed today that  the `NamedTuples.create_tuple` method has been refactored / renamed but JuliaDB still contains a reference to that in utils.jl, line 359 method `Base.deserialize`.

**Comment by shashi** [comment]
Thanks! It looks like that change hasn't been released yet https://github.com/JuliaLang/METADATA.jl/pull/9525 . I fixed it anyway to keep it working with warnings when it is released. The correct fix here is to remove the `Base.serialize` and `Base.deserialize` methods. Which I can do once a new NamedTuples is released.

Cheers!
