### ISSUE TITLE
Merge vs Union

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaComputing/JuliaDB.jl#65]
Is the merge function intended to enable performing SQL style `union` operations.
If so how should it handle empty arguments?

**Comment by shashi** [comment]
Yes, `merge` is a union join... What do you mean by empty arguments?

**Comment by shashi** [comment]
Okay now I understand this, and have implemented union join in (called outerjoin) in https://github.com/JuliaComputing/IndexedTables.jl/pull/85, it's coming to distributed soon.

`merge` is a form of concatenation which preserves the order by the key columns. This will remain as it is.

**Comment by shashi** [comment]
We now have `outerjoin`!
