### ISSUE TITLE
Reducedim issue

### ISSUE THREAD

**Issue by iyever** [JuliaComputing/JuliaDB.jl#87]
reducedim function errors out with StackOverflowError when the aggregation function is executed over 99 times

Example:
```jl
t = distribute(IndexedTable([fill(1,100000); fill(2,100000); fill(3,100000);fill(4,100000);fill(5,100000)],
                            rand(Float64,500000), fill(1,500000),
                            MVector{64,Float64}[rand(Float64, 64) for n in 1:500000]), 2)

compute(reducedim((x,y)->MVector(x+y), t, 1)) - works

compute(reducedim((x,y)->MVector(x+y), t, 2)) – StackOverflowError. Complains the function executed > 99 times           
```

**Comment by shashi** [comment]
This works for me locally...

**Comment by iyever** [comment]
The strange thing is it is now works for me if I try to reducedim my cube in REPL, but does not work in the real environment. 
[ScenTest.txt](https://github.com/JuliaComputing/JuliaDB.jl/files/1427928/ScenTest.txt)

I've attached a test file. This is the same I sent you on 10/4/17 asking to look into performance. It can be used with the same data.

**Comment by iyever** [comment]
Was my error
