### ISSUE TITLE
Implement fit!(Series, DTable)

### ISSUE THREAD

**Issue by andreasnoack** [JuliaComputing/JuliaDB.jl#89]
Right now we can't update a series. We can use merge but that is not good for histograms where the two histograms might not have the same bins.

**Comment by andreasnoack** [comment]
@joshday What is your current thinking here. Should this be done in a different way such that this can be closed?

**Comment by joshday** [comment]
Right now `reduce` copies a `Series` argument.  It's on my list of things to do to change it to non-copying so things like

```julia
s = Series(Hist(50))
reduce(s, mytable, select = :x)
reduce(s, anothertable, select = :x)
plot(s)
```

will work as expected.  It requires a few changes that I haven't had time to dig into the details, but it should be fairly straightforward to do.

**Comment by joshday** [comment]
The workaround for now is:

```julia
s = Series(Hist(20))
s = reduce(s, mytable; select=:x)
s = reduce(s, anothertable; select=:x)
plot(s)
```

**Comment by joshday** [comment]
I think we should use `reduce`.  Last time I looked into making `reduce` non-copying I found an issue in JuliaDB, but everything seemed fine in IndexedTables.  Sorting that out is on my to-do list, but low priority right now.

**Comment by shashi** [comment]
Okay then. Yeah, I think we copy Stats (in JuliaDB) while merging results from different procs.
