### ISSUE TITLE
Allow save on non-distributed data

### ISSUE THREAD

**Issue by sdmcallister** [JuliaComputing/JuliaDB.jl#94]
Hi,
When I try to save a table I see the following MethodError:

`using JuliaDB`
`t=table(collect(1:5),rand(1:100,5),names=[:x,:y])`
`save(t,"C:\\Users\\sdmca\\Desktop\\")`
`ERROR: MethodError: no method matching save(::IndexedTables.NextTable{IndexedTables.Columns{NamedTuples._NT_x_y{Int64,Int64},NamedTuples._NT_x_y{Array{Int64,1},Array{Int64,1}}}}, ::String)
Closest candidates are:
  save(::Any, ::IO, ::Dagger.Chunk, ::Any) at C:\Users\sdmca\.julia\v0.6\Dagger\src\file-io.jl:55
  save(::Any, ::IO, ::Dagger.DArray, ::AbstractString, ::AbstractArray) at C:\Users\sdmca\.julia\v0.6\Dagger\src\file-io.jl:72
  save(::Any, ::IO, ::Dagger.DArray, ::Any) at C:\Users\sdmca\.julia\v0.6\Dagger\src\file-io.jl:84
  ...`

Am I doing something wrong on my end?

**Comment by shashi** [comment]
`save` currently works on distributed datasets only. Try
```
t=table(collect(1:5),rand(1:100,5),names=[:x,:y], chunks=1)
save(t,"C:\\Users\\sdmca\\Desktop\\data")
```

**Comment by andreasnoack** [comment]
Bump. It would be great to have this working in the non-distributed case as well.

**Comment by shashi** [comment]
I almost have this. Not to worry!
